services:
  - type: web
    name: hygene-store-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8081
      - key: DATABASE_URL
        fromDatabase:
          name: hygene-store-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: hygene-store-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: hygene-store-db
          property: password
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET
        sync: false
databases:
  - name: hygene-store-db
    plan: free
